- src/components/home/TrustedBy/companies.ts
> Update SushiSwap link

- src/components/security/BugBounty/index.tsx
Update the URL that links to information about bug bounties
> Fix bug bounty link

- .github/workflows/deployments.yml
- scripts/prepare_production_deployment.sh
Prepares these deployment environments:
- Production: https://gnosis-safe.io (manual deployment)
- Staging: http://safe-team.staging.gnosisdev.com
- Development: http://safe-team.dev.gnosisdev.com
> Add deploy github action

- .gitignore
- src/pages/privacy.tsx
> Update privacy policy page to include section for Beamer

- .gitignore
- package.json
- src/pages/cookie.tsx
- src/pages/privacy.tsx
> Release 2.6.1

- package.json
- src/pages/privacy.tsx
> Back-merge from main + bump version

- package.json
- src/utils/CookiesBanner.tsx
- src/utils/cookies.ts
> Release 2.6.2

- src/components/security/Description.tsx
> Update statistics within Security section 

- package.json
- src/components/security/Description.tsx
Merge `dev` into `main`:
- #30
> Release v2.6.3

- package.json
- https://github.com/gnosis/safe-landing-page/pull/32
> Release 2.6.4

- src/components/careers/Locations/Card.tsx
- src/components/careers/Locations/index.tsx
- src/components/careers/Locations/locations.ts
- src/pages/careers.tsx
Add location card component
_mobile_
> feat: Component location card

- src/assets/map-pin.svg
- src/components/careers/Positions/Card.tsx
- src/components/careers/Positions/index.tsx
- src/components/careers/Positions/usePositions.ts
- src/pages/careers.tsx
Fetches open positions from greenhouse api and displays job listings in a 3x3 grid
> feat: Add Open positions component

- src/components/careers/Footer/index.tsx
- src/components/careers/Leadership/Card.tsx
- src/pages/careers.tsx
Adds footer section to the careers page
> feat: Add footer to careers page

- src/components/Layout/ContentWrapper.tsx
- src/components/Layout/Header/Mobile/MobileMenu.tsx
- src/components/careers/Benefits/Card.tsx
- src/components/careers/Benefits/index.tsx
- src/components/careers/Footer/index.tsx
- src/components/careers/Header/index.tsx
- src/components/careers/InitiativeApplication/index.tsx
- src/components/careers/Leadership/Card.tsx
- src/components/careers/Leadership/index.tsx
- src/components/careers/Locations/Card.tsx
- src/components/careers/Locations/index.tsx
- src/components/careers/MostTrusted/index.tsx
- src/components/careers/Positions/Card.tsx
- src/components/careers/Positions/index.tsx
- src/components/careers/styled.ts
- src/styles/global.css
- src/styles/styleUtils.ts
Adjusts the layout, typography and spaces of the careers page
> style: Careers page layout

- package.json
- src/components/Layout/Header/Dropdown.tsx
- src/components/Layout/Header/Header.tsx
Add new entry to the menu pointing to the Safe Guardians page.
> Safe guardians

- package.json
- src/utils/CookiesBanner.tsx
> Back merge Main into Dev

- package.json
- src/assets/mirror.svg
- src/components/careers/InitiativeApplication/index.tsx
- src/components/careers/Locations/Card.tsx
- src/components/careers/Locations/locations.ts
- src/components/home/Social.tsx
> Fix: mirror links and Berlin address

- .github/workflows/cla.yml
- README.md
- src/components/developers/Contracts.tsx
- src/components/developers/Repositories.tsx
- src/components/home/Clients/DownloadButtons.tsx
- src/components/security/Audits.tsx
- src/components/security/FormallyVerified.tsx
- src/pages/licenses.tsx
- src/pages/terms.tsx
Update Github links:
`/gnosis/` => `/safe-global/`
> Fix: Update Github links

- src/components/careers/Positions/index.tsx
- src/components/careers/Positions/usePositions.ts
WIP: Wait with merge until go from HR 
Switches Job listing API integration from greenhouse to breezy
Should look the same
> fix: Switch from greenhouse to breezy for job listings

- package.json
- https://github.com/safe-global/safe-landing-page/pull/59
> Release v2.8.1

- package.json
- src/components/careers/Benefits/index.tsx
> Release v2.8.2

- package.json
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Header/Mobile/MobileMenu.tsx
- src/components/home/Clients/DownloadButtons.tsx
- src/components/home/GettingStarted.tsx
It links to the new app subdomain now.
> Fix: update web app links

- package.json
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Header/Mobile/MobileMenu.tsx
- src/components/home/Clients/DownloadButtons.tsx
- src/components/home/GettingStarted.tsx
* Fix: link to the new app domain
> Release 3.9.3

- package.json
- src/components/Layout/Header/Header.tsx
- src/components/home/Social.tsx
- src/pages/terms.tsx
Updates the chat links to chat.safe.global
> fix: Update chat link

- .github/workflows/cla.yml
- package.json
- src/pages/cla.tsx
Resolves #90.
Gnosis has been replaced with SEF in the text + a new email address.
> Fix: update the CLA page

- .github/workflows/cla.yml
- package.json
- src/pages/cla.tsx
* Fix: update the CLA page (#91)
(Do NOT merge via GitHub!)
> Release v2.9.8

- package.json
Includes:
- https://github.com/safe-global/safe-landing-page/pull/96
> Version 2.9.10
